CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE universities (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(80) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE publication_type AS ENUM ('UBER_SPLIT', 'OWN_CAR', 'RIDE_REQUEST');
