-- PERSONA 2
--
-- Datos ficticios para desarrollo.
-- NO usar datos personales reales.
--
-- TODO:
-- - usuarios ficticios
-- - publicaciones ficticias de los tres tipos oficiales:
--   UBER_SPLIT, OWN_CAR, RIDE_REQUEST
