spring.application.name=greenmove
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/greenmove_db
spring.datasource.username=greenmove_user
spring.datasource.password=greenmove_dev_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.time-zone=America/Mexico_City

app.frontend-url=http://localhost:5173
